# Modern RNN (Recurrent Neural Networks)

### 循环神经网络进阶

**- GRU(Gated Recurrent Unit) 门控循环网络 LSTM变体 **

**- LSTM(Long-Short-Term-Memories) 长短期记忆网络 **

**- 深层RNN **

**- 双向RNN**

# 参考资料

#### GRU与LSTM总结
https://blog.csdn.net/lreaderl/article/details/78022724

# 习题

选择题

### 1.LSTM单元中控制当前时间步输入的结构是？

A.遗忘门

B.输入门

C.输出门

D.记忆细胞

#### 答案：B

答案解释

参考视频中输入门的定义

### 2.实现深层循环神经网络需要修改的参数是？

A.input_size

B.hidden_size

C.bidirectional

D.num_layers

#### 答案：D

答案解释

参考视频24分50秒左右

### 3.下列关于GRU说法正确的是？

A.GRU有遗忘门、更新门两种门控结构

B.GRU中重置门有助于捕捉时间序列里长期的依赖关系

C.GRU中更新门有助于捕捉时间序列里长期的依赖关系

D.GRU中遗忘门有助于捕捉时间序列里长期的依赖关系

#### 答案：C

答案解释

GRU有重置门和更新门，没有遗忘门。重置门有助于捕捉时间序列里短期的依赖关系，更新门有助于捕捉时间序列⾥长期的依赖关系。参考视频1分20秒起关于GRU的原理讲解。

### 4.在LSTM模型的初始化中，下列不需要初始化的参数是？

A.每个循环单元中的记忆细胞和循环单元的值

B.第0个循环单元的记忆细胞和循环单元的值

C.门控单元中用于计算遗忘门的权重与偏差

D.用于计算输出的权重与偏差

#### 答案：A

答案解释

每个循环单元中的记忆细胞和循环单元的值为LSTM模型中的隐状态，而非参数，因此不需要初始化。

### 5.下列关于RNN的说法错误的是？

A.GRU、LSTM都能捕捉时间序列中时间步距离较⼤的依赖关系。

B.双向循环神经网络在文本任务里能做到同时考虑上文和下文与当前词之间的依赖。

C.LSTM和GRU能一定程度缓解梯度消失与梯度爆炸的问题。

D.深层循环网络能有效抽取更高层更抽象的信息，层数越深效果越好。

#### 答案：D

答案解释

层数越深效果未必越好，层数的加深会导致模型的收敛变得困难。

### 6.双向循环神经网络前向和后向RNN连结的方式是

A.前向的output和后向的output用concat进行连结

B.前向的$H_t$和后向的$H_t$用concat进行连结

C.前向的output和后向的output按元素相加

D.前向的$H_t$和后向的$H_t$按元素相加

#### 答案：B

答案解释

参考视频27分45秒左右。


In [12]:
import torch

x = torch.ones(10)
w = 2.5

In [10]:
x

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
y = x * w

In [14]:
y

tensor([2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000, 2.5000,
        2.5000])

In [16]:
x = torch.randn(10, 2)

In [17]:
x

tensor([[-0.5505, -0.6513],
        [-0.1308,  0.8378],
        [-1.5610, -0.5843],
        [-0.9865,  0.5920],
        [-0.7375, -0.4201],
        [ 2.2606,  0.9286],
        [ 0.7264, -1.3176],
        [-0.4865, -0.9557],
        [ 0.0201,  0.9662],
        [-0.8094,  3.3333]])

In [26]:
w1 = torch.tensor([2])
w2 = torch.tensor([[2],[4]])

In [27]:
y = w1 * w2

In [25]:
y

tensor([[ 4,  6],
        [ 8, 12]])

In [28]:
y

tensor([[4],
        [8]])

In [52]:
x3 = torch.tensor([[2, 1],
                   [4, 3],
                   [1,3]])
w3 =[2, 3]
y3 = w3[0] * x3[:,0]

In [53]:
y3

tensor([4, 8, 2])

In [54]:
y4 = w3[1] * x3[:,1]
y4

tensor([3, 9, 9])

In [55]:
x3

tensor([[2, 1],
        [4, 3],
        [1, 3]])

In [56]:
H = y3 + y4
H

tensor([ 7, 17, 11])

In [57]:
x3.shape

torch.Size([3, 2])

In [58]:
H.shape

torch.Size([3])

In [59]:
X = torch.arange(10).view(2, 5)

In [60]:
X

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
vocab_size = 1027
n_class = 1027
def one_hot(x, n_class, dtype=torch.float32):
    result = torch.zeros(x.shape[0], n_class, dtype=dtype, device=x.device)  # shape: (n, n_class)
    result.scatter_(1, x.long().view(-1, 1), 1)  # result[i, x[i, 0]] = 1
    return result

def to_onehot(X, n_class):
    return [one_hot(X[:, i], n_class) for i in range(X.shape[1])]

X = torch.arange(10).view(2, 5)
inputs = to_onehot(X, vocab_size)
print(len(inputs), inputs[0].shape)

5 torch.Size([2, 1027])


In [67]:
one_hot(X[:, 0],1027)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [69]:
X[:, 0]

tensor([0, 5])

In [70]:
X

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
inputs[1].shape

torch.Size([2, 1027])